name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make

    - name: Check for warnings
      run: make CFLAGS="-std=c11 -Wall -Wextra -Werror -O2"
